import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/ControlSystem/Footer";
import TopMenu from "@/components/ControlSystem/TopMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ShopDee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <TopMenu/>
        <main className="container mx-auto mt-[navbarHeight] px-4 py-6">
            {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
