
export const products: Product[] = [
  {
    id:1,
    name: "Pen",
    images: ["https://drive.google.com/file/d/1U6A2V0p75m4jHGLiP7oQQ6J-LQSLLU5S/view?usp=drive_link",
              "https://drive.google.com/file/d/1jgOhPxuNtkcpNmLwy5q4Q1BvfMwDwg67/view?usp=drive_link",
              "https://drive.google.com/file/d/1cHhv_3Oadvvrs73bIBaCpvKQ0plki89X/view?usp=drive_link",
              "https://drive.google.com/file/d/1Qr5H0Jyt-fE9Ae60U4kuazkBK4frsWAe/view?usp=drive_link"],
    cost: 200,
    discount: 10,
    detail: "A high-quality pen for smooth writing.",
    category: "Writing Instruments",
    stock: 10,
    sold: 5,
    types:["red", "blue", "green", "yellow", "orange", "purple", "white"],
    storeId: {
      id:1,
      name: "store1",
      detail: "This store is very good",
      image: "/img/item/1/profile.png",
      banner: "banner",
    }
  },
  {
    id:2,
    name: "Notebook",
    images: ["/img/item/2/1.png", "/img/item/2/2.png", "/img/item/2/3.png", "/img/item/2/4.png"],
    cost: 500,
    discount: 10,
    detail: "A durable notebook with lined pages for taking notes.",
    category: "Paper Products",
    stock: 10,
    sold: 5,
    types:["red", "blue", "green", "yellow", "orange", "purple", "white"],
    storeId: {
      id:2,
      name: "store2",
      detail: "This store offers a wide range of paper products.",
      image: "/img/item/2/profile.png",
      banner: "banner2",
    }
  },
  {
    id:3,
    name: "Eraser",
    images: ["/img/item/3/1.png", "/img/item/3/2.png", "/img/item/3/3.png", "/img/item/3/4.png"],
    cost: 50,
    discount: 10,
    detail: "A soft and effective eraser for correcting mistakes.",
    category: "Writing Instruments",
    stock: 10,
    sold: 5,
    types:["red", "blue", "green", "yellow", "orange", "purple", "white"],
    storeId: {
      id:3,
      name: "store3",
      detail: "This store specializes in writing instruments.",
      image: "/img/item/3/profile.png",
      banner: "banner3",
    }
  },
  {
    id:4,
    name: "Pencil",
    images: ["/img/item/4/1.png", "/img/item/4/2.png", "/img/item/4/3.png", "/img/item/4/4.png"],
    cost: 100,
    discount: 10,
    detail: "A classic pencil for writing and drawing.",
    category: "Writing Instruments",
    stock: 10,
    sold: 5,
    types:["red", "blue", "green", "yellow", "orange", "purple", "white"],
    storeId: {
      id:3,
      name: "store3",
      detail: "This store specializes in writing instruments.",
      image: "/img/item/3/profile.png",
      banner: "banner3",
    }
  },
  {
    id:5,
    name: "Ruler",
    images: ["/img/item/5/1.png", "/img/item/5/2.png", "/img/item/5/3.png", "/img/item/5/4.png"],
    cost: 80,
    discount: 10,
    detail: "A sturdy ruler for measuring and drawing straight lines.",
    category: "Drafting Tools",
    stock: 10,
    sold: 5,
    types:["red", "blue", "green", "yellow", "orange", "purple", "white"],
    storeId: {
      id:4,
      name: "store4",
      detail: "This store offers a variety of drafting tools.",
      image: "/img/item/4/profile.png",
      banner: "banner4",
    }
  },
  {
    id:6,
    name: "Marker",
    images: ["/img/item/6/1.png", "/img/item/6/2.png", "/img/item/6/3.png", "/img/item/6/4.png"],
    cost: 110,
    discount: 10,
    detail: "A vibrant marker for highlighting and writing on various surfaces.",
    category: "Writing Instruments",
    stock: 10,
    sold: 5,
    types:["red", "blue", "green", "yellow", "orange", "purple", "white"],
    storeId: {
      id:3,
      name: "store3",
      detail: "This store specializes in writing instruments.",
      image: "/img/item/3/profile.png",
      banner: "banner3",
    }
  },
  {
    id:7,
    name: "Glue Stick",
    images: ["/img/item/7/1.png", "/img/item/7/2.png", "/img/item/7/3.png", "/img/item/7/4.png"],
    cost: 90,
    discount: 10,
    detail: "A convenient glue stick for adhering paper and other materials.",
    category: "Adhesives",
    stock: 10,
    sold: 5,
    types:["red", "blue", "green", "yellow", "orange", "purple", "white"],
    storeId: {
      id:5,
      name: "store5",
      detail: "This store offers a wide range of adhesives and craft supplies.",
      image: "/img/item/5/profile.png",
      banner: "banner5",
    }
  },
  {
    id:8,
    name: "Scissors",
    images: ["/img/item/8/1.png", "/img/item/8/2.png", "/img/item/8/3.png", "/img/item/8/4.png"],
    cost: 250,
    discount: 10,
    detail: "Sharp scissors for cutting paper and other materials.",
    category: "Cutting Tools",
    stock: 10,
    sold: 5,
    types:["red", "blue", "green", "yellow", "orange", "purple", "white"],
    storeId: {
      id:6,
      name: "store6",
      detail: "This store specializes in cutting tools and blades.",
      image: "/img/item/6/profile.png",
      banner: "banner6",
    }
  },
  {
    id:9,
    name: "Stapler",
    images: ["/img/item/9/1.png", "/img/item/9/2.png", "/img/item/9/3.png", "/img/item/9/4.png"],
    cost: 300,
    discount: 10,
    detail: "A reliable stapler for binding papers together.",
    category: "Office Supplies",
    stock: 10,
    sold: 5,
    types:["red", "blue", "green", "yellow", "orange", "purple", "white"],
    storeId: {
      id:7,
      name: "store7",
      detail: "This store offers a wide range of office supplies.",
      image: "/img/item/7/profile.png",
      banner: "banner7",
    }
  },
  {
    id:10,
    name: "Highlighter",
    images: ["/img/item/10/1.png", "/img/item/10/2.png", "/img/item/10/3.png", "/img/item/10/4.png"],
    cost: 120,
    discount: 10,
    detail: "A fluorescent highlighter for emphasizing important text.",
    category: "Writing Instruments",
    stock: 10,
    sold: 5,
    types:["red", "blue", "green", "yellow", "orange", "purple", "white"],
    storeId: {
      id:3,
      name: "store3",
      detail: "This store specializes in writing instruments.",
      image: "/img/item/3/profile.png",
      banner: "banner3",
    }
  },
  {
    id:11,
    name: "Paper Clips",
    images: ["/img/item/11/1.png", "/img/item/11/2.png", "/img/item/11/3.png", "/img/item/11/4.png"],
    cost: 30,
    discount: 10,
    detail: "A pack of paper clips for organizing and securing documents.",
    category: "Office Supplies",
    stock: 10,
    sold: 5,
    types:["red", "blue", "green", "yellow", "orange", "purple", "white"],
    storeId: {
      id:7,
      name: "store7",
      detail: "This store offers a wide range of office supplies.",
      image: "/img/item/7/profile.png",
      banner: "banner7",
    }
  },
  {
    id:12,
    name: "Binder",
    images: ["/img/item/12/1.png","/img/item/12/2.png","/img/item/12/3.png","/img/item/12/4.png"],
    cost: 400,
    discount: 10,
    detail: "A sturdy binder for keeping papers and documents organized.",
    category: "Paper Products",
    stock: 10,
    sold: 5,
    types:["red", "blue", "green", "yellow", "orange", "purple", "white"],
    storeId: {
      id:7,
      name: "store7",
      detail: "This store offers a wide range of office supplies.",
      image: "/img/item/7/profile.png",
      banner: "banner7",
    }
  },
  {
    id:13,
    name: "Calculator",
    images: ["/img/item/13/1.png","/img/item/13/2.png","/img/item/13/3.png","/img/item/13/4.png"],
    cost: 800,
    discount: 10,
    detail: "A reliable calculator for performing mathematical calculations.",
    category: "Office Supplies",
    stock: 10,
    sold: 5,
    types:["red", "blue", "green", "yellow", "orange", "purple", "white"],
    storeId: {
      id:7,
      name: "store7",
      detail: "This store offers a wide range of office supplies.",
      image: "/img/item/7/profile.png",
      banner: "banner7",
    }
  },
  {
    id:14,
    name: "Backpack",
    images: ["/img/item/14/1.png","/img/item/14/2.png","/img/item/14/3.png","/img/item/14/4.png"],
    cost: 600,
    discount: 10,
    detail: "A spacious backpack for carrying books and supplies.",
    category: "Bags",
    stock: 10,
    sold: 5,
    types:["red", "blue", "green", "yellow", "orange", "purple", "white"],
    storeId: {
      id:7,
      name: "store7",
      detail: "This store offers a wide range of office supplies.",
      image: "/img/item/7/profile.png",
      banner: "banner7",
    }
  },
  {
    id:15,
    name: "Whiteboard",
    images: ["/img/item/15/1.png","/img/item/15/2.png","/img/item/15/3.png","/img/item/15/4.png"],
    cost: 1200,
    discount: 10,
    detail: "A large whiteboard for writing notes and ideas.",
    category: "Writing Surfaces",
    stock: 10,
    sold: 5,
    types:["red", "blue", "green", "yellow", "orange", "purple", "white"],
    storeId: {
      id:7,
      name: "store7",
      detail: "This store offers a wide range of office supplies.",
      image: "/img/item/7/profile.png",
      banner: "banner7",
    }
  }
];