export const products = [
  {
    name: "Pen",
    picture: "/img/item/1.png",
    price: "200",
    oldprice: "300",
    selled: "127",
  },
  {
    name: "Notebook",
    picture: "/img/item/2.png",
    price: "500",
    oldprice: "600",
    selled: "98",
  },
  {
    name: "Eraser",
    picture: "/img/item/3.png",
    price: "50",
    oldprice: "80",
    selled: "150",
  },
  {
    name: "Pencil",
    picture: "/img/item/4.png",
    price: "100",
    oldprice: "150",
    selled: "210",
  },
  {
    name: "Ruler",
    picture: "/img/item/5.png",
    price: "80",
    oldprice: "120",
    selled: "75",
  },
  {
    name: "Marker",
    picture: "/img/item/6.png",
    price: "150",
    oldprice: "200",
    selled: "60",
  },
  {
    name: "Glue Stick",
    picture: "/img/item/7.png",
    price: "90",
    oldprice: "130",
    selled: "85",
  },
  {
    name: "Scissors",
    picture: "/img/item/8.png",
    price: "250",
    oldprice: "350",
    selled: "40",
  },
  {
    name: "Stapler",
    picture: "/img/item/9.png",
    price: "300",
    oldprice: "400",
    selled: "55",
  },
  {
    name: "Highlighter",
    picture: "/img/item/10.png",
    price: "120",
    oldprice: "170",
    selled: "132",
  },
  {
    name: "Paper Clips",
    picture: "/img/item/11.png",
    price: "30",
    oldprice: "50",
    selled: "220",
  },
  {
    name: "Binder",
    picture: "/img/item/12.png",
    price: "400",
    oldprice: "500",
    selled: "35",
  },
  {
    name: "Calculator",
    picture: "/img/item/13.png",
    price: "800",
    oldprice: "1000",
    selled: "70",
  },
  {
    name: "Backpack",
    picture: "/img/item/14.png",
    price: "1500",
    oldprice: "2000",
    selled: "22",
  },
  {
    name: "Whiteboard",
    picture: "/img/item/15.png",
    price: "1200",
    oldprice: "1500",
    selled: "18",
  },
];
